name: CulinaChef
options:
  minimumXcodeGenVersion: 2.37.0
  developmentLanguage: de
  knownRegions:
    - de
    - en
    - es
    - fr
    - it
packages:
  Sentry:
    url: https://github.com/getsentry/sentry-cocoa.git
    from: 8.57.0
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    SWIFT_VERSION: 5.9
    DEVELOPMENT_TEAM: "4Q33QP9G7Z"
    ALWAYS_SEARCH_USER_PATHS: NO
targets:
  CulinaChef:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Sources
    resources:
      - path: Resources
        type: folder
    dependencies:
      - package: Sentry
        product: Sentry
    configFiles:
      Debug: Configs/Secrets.xcconfig
      Release: Configs/Secrets.xcconfig
    info:
      path: Sources/Info.plist
      properties:
        CFBundleIdentifier: com.moritzserrin.culinachef
        UIUserInterfaceStyle: Automatic
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UIRequiresFullScreen: true
        UILaunchStoryboardName: LaunchScreen
        NSCameraUsageDescription: "Zum Fotografieren deiner Zutaten für Rezeptvorschläge."
        NSPhotoLibraryAddUsageDescription: "Zum Speichern/Verarbeiten von Fotos deiner Zutaten."
        NSPhotoLibraryUsageDescription: "Zum Auswählen von Bildern aus deiner Galerie für Rezeptvorschläge."
        OpenAIAPIKey: $(OPENAI_API_KEY)
        SentryDSN: $(SENTRY_DSN)
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
    settings:
      base:
        PRODUCT_NAME: CulinaChef
        PRODUCT_BUNDLE_IDENTIFIER: com.moritzserrin.culinachef
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    scheme:
      testTargets:
        - CulinaChefTests
      gatherCoverageData: true

  CulinaChefTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Tests
    dependencies:
      - target: CulinaChef
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.moritzserrin.culinachef.tests
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: YES
