name: CulinaChef
options:
  minimumXcodeGenVersion: 2.37.0
  developmentLanguage: de
  knownRegions:
    - de
    - en
    - es
    - fr
    - it
  usesTabs: false
  groupSortPosition: top
  createIntermediateGroups: true
packages:
  Sentry:
    url: https://github.com/getsentry/sentry-cocoa.git
    from: 8.57.0
  RevenueCat:
    url: https://github.com/RevenueCat/purchases-ios-spm.git
    from: 5.49.2
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    SWIFT_VERSION: 5.9
    DEVELOPMENT_TEAM: "4Q33QP9G7Z"
    ALWAYS_SEARCH_USER_PATHS: NO
    SWIFT_ENABLE_EXPLICIT_MODULES: YES
    SWIFT_EMIT_MODULE_SEPARATELY: NO
targets:
  CulinaChef:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Sources
    resources:
      - path: Resources
        type: folder
      - path: Configs/StoreKit.storekit
        optional: false
    dependencies:
      - package: Sentry
        product: Sentry
      - package: RevenueCat
        product: RevenueCat
      - target: CulinaChefTimerWidget
        embed: true
        codeSignOnCopy: true
        removeHeadersOnCopy: true
    configFiles:
      Debug: Configs/Secrets.xcconfig
      Release: Configs/Secrets.xcconfig
    entitlements:
      path: Configs/CulinaChef.entitlements
    info:
      path: Sources/Info.plist
      properties:
        CFBundleIdentifier: com.moritzserrin.culinachef
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UIRequiresFullScreen: true
        UILaunchStoryboardName: LaunchScreen
        NSCameraUsageDescription: "Zum Fotografieren deiner Zutaten für Rezeptvorschläge."
        NSPhotoLibraryAddUsageDescription: "Zum Speichern/Verarbeiten von Fotos deiner Zutaten."
        NSPhotoLibraryUsageDescription: "Zum Auswählen von Bildern aus deiner Galerie für Rezeptvorschläge."
        SupabaseURL: $(SUPABASE_URL)
        SupabaseAnonKey: $(SUPABASE_ANON_KEY)
        OpenAIAPIKey: $(OPENAI_API_KEY)
        SentryDSN: $(SENTRY_DSN)
        RevenueCatAPIKey: $(REVENUECAT_API_KEY)
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - culinachef
            CFBundleURLName: com.moritzserrin.culinachef
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
    settings:
      base:
        PRODUCT_NAME: CulinaChef
        PRODUCT_BUNDLE_IDENTIFIER: com.moritzserrin.culinachef
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      configs:
        Release:
          DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
          COPY_PHASE_STRIP: NO
    scheme:
      testTargets:
        - CulinaChefTests
      gatherCoverageData: true

  CulinaChefTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Tests
    dependencies:
      - target: CulinaChef
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.moritzserrin.culinachef.tests
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: YES

  CulinaChefTimerWidget:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Widgets
        excludes:
          - "**/Info.plist"  # Info.plist wird über info: path referenziert
          - "**/*.sh"  # Exclude shell scripts from widget bundle
          - "**/*.md"  # Exclude markdown documentation files
    entitlements:
      path: Configs/CulinaChefWidget.entitlements
    info:
      path: Widgets/Info.plist
    settings:
      base:
        PRODUCT_NAME: CulinaChefTimerWidget
        PRODUCT_BUNDLE_IDENTIFIER: com.moritzserrin.culinachef.widget
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: YES  # Allow entitlements to be modified if needed
        INFOPLIST_KEY_CFBundleDisplayName: "Koch-Timer"
        INFOPLIST_KEY_NSHumanReadableCopyright: ""
        INFOPLIST_KEY_NSExtension_NSExtensionPointIdentifier: com.apple.widgetkit-extension
        INFOPLIST_KEY_CFBundlePackageType: XPC!
        INFOPLIST_KEY_CFBundleVersion: 1
        INFOPLIST_KEY_CFBundleShortVersionString: 1.0
        GENERATE_INFOPLIST_FILE: NO  # Use manual Info.plist, don't generate
        SKIP_INSTALL: NO
    scheme:
      testTargets: []
      buildAction:
        targets:
          - CulinaChefTimerWidget
      runAction:
        executable: ""
        askForAppToLaunch: false
